version: "3.8"

services:
  db:
    build: ./mysql
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

  cache:
    build: ./redis
    volumes:
      - ./redis/data:/data
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]

  cache-gui:
    image: patrikx3/p3x-redis-ui:latest
    ports:
      - 7843:7843
    volumes:
      - ./redis/gui:/settings
    depends_on:
      - cache

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    command: yarn dev
    volumes:
      - .:/usr/src/app
      - app_data:/usr/src/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
      - cache

volumes:
  db_data: {}
  app_data: {}
